spring.application.name=Bankinc

# Conexión SQLite
spring.datasource.url=jdbc:sqlite:bankinc.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Dialecto para SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Hibernate crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true